version: '3.1'
services:
  db:
    image: postgres
    restart: always
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: south-african-numbers-validator
    volumes:
      - ./backup:/backup
    ports:
      - '5433:5432'
